pipeline {
    agent any

    stages {

        stage('Build & Test') {
            steps {
                dir('BankingAutomationFramework') {
                    bat 'mvn clean test'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'BankingAutomationFramework/reports/*.html',
                    allowEmptyArchive: true

            archiveArtifacts artifacts: 'BankingAutomationFramework/screenshots/*.png',
                    allowEmptyArchive: true
        }
    }
}