pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                bat 'mvn clean test'
            }
        }
    }

    post {

        always {

            archiveArtifacts artifacts: 'screenshots/*.png',
                    allowEmptyArchive: true

            archiveArtifacts artifacts: 'reports/*.html',
                    allowEmptyArchive: true
        }
    }
}